export const projects = [
  {
    id: 1,
    title: "Skyline University",
    category: "NextJS",
    image: "/projects/skyline-website.png",
    link: "https://skyline-university.vercel.app/",
  },
  {
    id: 2,
    title: "Lovely Maldives Website",
    category: "MERN",
    image: "/projects/lovely-maldives-website.png",
    link: "https://lovely-maldives-static.vercel.app/",
  },
  {
    id: 3,
    title: "Advice Care",
    category: "ReactJS",
    image: "/projects/advice-care.png",
    link: "https://advicecare.vercel.app/experts",
  },
  {
    id: 4,
    title: "Skyline Dashboard",
    category: "NextJS",
    image: "/projects/skyline-university-dashboard.png",
    link: "https://skyline-university-dashboard.vercel.app/dashboards/ecommerce-dashboard",
  },
  {
    id: 5,
    title: "The Credit Pros",
    category: "MERN",
    image: "/projects/credit-pros.png",
    link: "https://the-credit-pros.vercel.app/",
  },
  {
    id: 6,
    title: "Ahya OS",
    category: "NextJS",
    image: "/projects/ahyaos.png",
    link: "https://ahya-os.vercel.app/",
  },
  {
    id: 7,
    title: "Ordering App",
    category: "NextJS",
    image: "/projects/ordering-app.png",
    link: "https://ordering-app-three.vercel.app/",
  },
  {
    id: 8,
    title: "Al-Busayra",
    category: "NextJS",
    image: "/projects/albusayra.png",
    link: "https://al-busayra-new.vercel.app/admin/campaigns",
  },
  {
    id: 9,
    title: "Smart Counsellor",
    category: "MERN",
    image: "/projects/smart-counsellor.png",
    link: "https://smart-counsellor-2-dev.vercel.app/super-admin",
  },
  {
    id: 10,
    title: "Glizzy",
    category: "MERN",
    image: "/projects/glizzy.png",
    link: "https://glizzy-alpha-dev.vercel.app/",
  },
  {
    id: 11,
    title: "Agent.ae",
    category: "MERN",
    image: "/projects/agent-ae.png",
    link: "https://agent-ae.vercel.app/",
  },
  {
    id: 12,
    title: "Meta Firenze",
    category: "MERN",
    image: "/projects/meta-firenze.png",
    link: "https://meta-firenze.vercel.app/",
  },
  {
    id: 13,
    title: "Brand Buddy",
    category: "ReactJS",
    image: "/projects/brand-buddy.png",
    link: "https://bbar-main-page.vercel.app/",
  },
  {
    id: 14,
    title: "The Temple of Groovy Eye",
    category: "ReactJS",
    image: "/projects/groovy-eye.png",
    link: "https://the-temple-of-groovey-eyes-hazel.vercel.app/",
  },
  {
    id: 15,
    title: "Kraut9",
    category: "ReactJS",
    image: "/projects/kraut.png",
    link: "https://kraut9-copy.vercel.app/",
  },
  {
    id: 16,
    title: "Wt-Capital",
    category: "ReactJS",
    image: "/projects/wt-capital.png",
    link: "https://wt-capital-final.vercel.app/",
  },
];
